// Code generated by "stringer -type=InterpreterResult"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Interpret_OK-0]
	_ = x[Interpret_Compile_Error-1]
	_ = x[Interpret_Runtime_Error-2]
}

const _InterpreterResult_name = "Interpret_OKInterpret_Compile_ErrorInterpret_Runtime_Error"

var _InterpreterResult_index = [...]uint8{0, 12, 35, 58}

func (i InterpreterResult) String() string {
	if i < 0 || i >= InterpreterResult(len(_InterpreterResult_index)-1) {
		return "InterpreterResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterpreterResult_name[_InterpreterResult_index[i]:_InterpreterResult_index[i+1]]
}
