// Code generated by "stringer -type=runtimeErrorCode -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[outOfBoundsPC-0]
	_ = x[popEmptyStack-1]
	_ = x[wrongType-2]
	_ = x[invalidOpCode-3]
}

const _runtimeErrorCode_name = "out of bounds program counterpop on an empty stackincorrect typeinvalid OpCode"

var _runtimeErrorCode_index = [...]uint8{0, 29, 50, 64, 78}

func (i runtimeErrorCode) String() string {
	if i < 0 || i >= runtimeErrorCode(len(_runtimeErrorCode_index)-1) {
		return "runtimeErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _runtimeErrorCode_name[_runtimeErrorCode_index[i]:_runtimeErrorCode_index[i+1]]
}
